apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-k8s
  name: go-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-k8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-k8s
    spec:
      containers:
      - image: brktsl/go-k8s:1.0.0
        name: go-k8s
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1         
        livenessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
status: {}
